### ISSUE TITLE
How exactly did you get this to work?

### ISSUE THREAD

**Issue by canna871** [kshpytsya/netlify-site-clone#1]
Hello, hope you are well. How did you get this to work exactly?

**Comment by kshpytsya** [comment]
Please describe what exactly you try to accomplish so that I would tell whether this is the right tool for the job. The tool isn't exactly well documented but with its code being a very straightforward I would expect anyone interested to be able to understand what it does.
Also, please note that it has been more than a year since the tool was actively used by me, so chances are that some recent changes in Netlify's API would prevent it from functioning as is.
If your use case is remotely matching the intended use of the tool, I may try verifying that it works with current Netlify's API and try writing a short description on "what" and "how".

**Comment by canna871** [comment]
> I meant like downloading and running the netlify apps locally. I guess it can autodeploy on another netfliy account, but netlify is quite easy to launch on, so the downloading or cloning part of it is interesting to me. 
For example how can I use the tool to clone https:/jpeg.netlify.app/ or https://mcap.netlify.app/ for example.

**Comment by kshpytsya** [comment]
This is not the intended use. I will now update the README to give a brief description.
